### ISSUE TITLE
TIAR Oled object theows compiler issues 

### ISSUE THREAD

**Issue by Korb-Modular** [zrna-research/akso-community#2]
This happens with I2c diplays: 
SSD 1306: 0.96",  1.3",  
SSD 1309 2.42" 
All these displays are working on the axoloti

`Generate code complete
Compiling patch.
Der Befehl "sed" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
process_begin: CreateProcess(NULL, sed -n s/^\/\/$MODULES=\(.*\)/\1/gp ../build/xpatch.cpp, ...) failed.
Makefile.patch:98: pipe: No such file or directory
process_begin: CreateProcess(NULL, sed -n s/^\/\/$MODULE_DIRS=\(.*\)/\1/gp ../build/xpatch.cpp, ...) failed.
Makefile.patch:99: pipe: No such file or directory
In file included from ../firmware/spilink.h:29,
                 from ../firmware/axoloti.h:33,
                 from ../firmware/xpatch.h:3:
../firmware/axoloti_control.h:21:18: error: expected identifier before numeric constant
 #define LCDWIDTH 128
                  ^~~
../build/xpatch.cpp:165:1: note: in expansion of macro 'LCDWIDTH'
 LCDWIDTH            = 128,
 ^~~~~~~~
../firmware/axoloti_control.h:21:18: error: expected '}' before numeric constant
 #define LCDWIDTH 128
                  ^~~
../build/xpatch.cpp:165:1: note: in expansion of macro 'LCDWIDTH'
 LCDWIDTH            = 128,
 ^~~~~~~~
../build/xpatch.cpp:164:14: note: to match this '{'
 enum SSD1306 {
              ^
In file included from ../firmware/spilink.h:29,
                 from ../firmware/axoloti.h:33,
                 from ../firmware/xpatch.h:3:
../firmware/axoloti_control.h:21:18: error: expected unqualified-id before numeric constant
 #define LCDWIDTH 128
                  ^~~
../build/xpatch.cpp:165:1: note: in expansion of macro 'LCDWIDTH'
 LCDWIDTH            = 128,
 ^~~~~~~~
../build/xpatch.cpp: In member function 'void rootc::fill(uint8_t)':
../build/xpatch.cpp:229:7: error: 'COLUMNADDR' was not declared in this scope
   cmd(COLUMNADDR);  cmd(0); cmd(127); // Column start end
       ^~~~~~~~~~
../build/xpatch.cpp:230:7: error: 'PAGEADDR' was not declared in this scope
   cmd(PAGEADDR);    cmd(0); cmd(  7); // Page start end
       ^~~~~~~~
../build/xpatch.cpp: In member function 'void rootc::_calcScopePage(int, uint8_t*)':
../build/xpatch.cpp:294:19: error: 'parent' was not declared in this scope
    uint16_t y = ((parent->instancescope__1_i.t[i]+64)*3 )/8;
                   ^~~~~~
../build/xpatch.cpp:294:19: note: suggested alternative: '_reent'
    uint16_t y = ((parent->instancescope__1_i.t[i]+64)*3 )/8;
                   ^~~~~~
                   _reent
../build/xpatch.cpp: In member function 'void rootc::sendTextPage(int)':
../build/xpatch.cpp:324:7: error: 'COLUMNADDR' was not declared in this scope
   cmd(COLUMNADDR);  cmd(0);    cmd(127);   // Column start end
       ^~~~~~~~~~
../build/xpatch.cpp:325:7: error: 'PAGEADDR' was not declared in this scope
   cmd(PAGEADDR);    cmd(page); cmd(page);  // Page start end
       ^~~~~~~~
../build/xpatch.cpp:342:13: error: 'parent' was not declared in this scope
     tY[i]=((parent->instancescope__1_i.t[i]+64)*3 )>>3;
             ^~~~~~
../build/xpatch.cpp:342:13: note: suggested alternative: '_reent'
     tY[i]=((parent->instancescope__1_i.t[i]+64)*3 )>>3;
             ^~~~~~
             _reent
../build/xpatch.cpp: In member function 'void rootc::init()':
../build/xpatch.cpp:350:7: error: 'DISPLAYOFF' was not declared in this scope
   cmd(DISPLAYOFF);
       ^~~~~~~~~~
../build/xpatch.cpp:353:7: error: 'SETDISPLAYCLOCKDIV' was not declared in this scope
   cmd(SETDISPLAYCLOCKDIV); cmd(0x80);
       ^~~~~~~~~~~~~~~~~~
../build/xpatch.cpp:354:7: error: 'SETMULTIPLEX' was not declared in this scope
   cmd(SETMULTIPLEX);  cmd(LCDHEIGHT - 1);
       ^~~~~~~~~~~~
../build/xpatch.cpp:355:7: error: 'SETDISPLAYOFFSET' was not declared in this scope
   cmd(SETDISPLAYOFFSET);  cmd(1306 == 1306 ? 0x00 : 0x01);
       ^~~~~~~~~~~~~~~~
../build/xpatch.cpp:356:7: error: 'SETSTARTLINE_0' was not declared in this scope
   cmd(SETSTARTLINE_0);
       ^~~~~~~~~~~~~~
../build/xpatch.cpp:357:7: error: 'CHARGEPUMP' was not declared in this scope
   cmd(CHARGEPUMP);     cmd(0x14);
       ^~~~~~~~~~
../build/xpatch.cpp:357:7: note: suggested alternative: 'HCCHAR_EPTYP'
   cmd(CHARGEPUMP);     cmd(0x14);
       ^~~~~~~~~~
       HCCHAR_EPTYP
../build/xpatch.cpp:358:7: error: 'MEMORYMODE' was not declared in this scope
   cmd(MEMORYMODE);     cmd(0x00);
       ^~~~~~~~~~
../build/xpatch.cpp:358:7: note: suggested alternative: 'REG_REMOVE'
   cmd(MEMORYMODE);     cmd(0x00);
       ^~~~~~~~~~
       REG_REMOVE
../build/xpatch.cpp:359:7: error: 'SEGREMAP' was not declared in this scope
   cmd(SEGREMAP | 0x1);
       ^~~~~~~~
../build/xpatch.cpp:360:7: error: 'COMSCANDEC' was not declared in this scope
   cmd(COMSCANDEC);
       ^~~~~~~~~~
../build/xpatch.cpp:362:7: error: 'SETCOMPINS' was not declared in this scope
   cmd(SETCOMPINS);     cmd(0x12);
       ^~~~~~~~~~
../build/xpatch.cpp:362:7: note: suggested alternative: 'STOPPING'
   cmd(SETCOMPINS);     cmd(0x12);
       ^~~~~~~~~~
       STOPPING
../build/xpatch.cpp:363:7: error: 'SETCONTRAST' was not declared in this scope
   cmd(SETCONTRAST);    cmd(0xCF);
       ^~~~~~~~~~~
../build/xpatch.cpp:363:7: note: suggested alternative: 'RTC_TR_ST'
   cmd(SETCONTRAST);    cmd(0xCF);
       ^~~~~~~~~~~
       RTC_TR_ST
../build/xpatch.cpp:364:7: error: 'SETPRECHARGE' was not declared in this scope
   cmd(SETPRECHARGE);   cmd(0xF1);
       ^~~~~~~~~~~~
../build/xpatch.cpp:365:7: error: 'SETVCOMDETECT' was not declared in this scope
   cmd(SETVCOMDETECT);  cmd(0x40);
       ^~~~~~~~~~~~~
../build/xpatch.cpp:366:7: error: 'DISPLAYALLON_RESUME' was not declared in this scope
   cmd(DISPLAYALLON_RESUME);
       ^~~~~~~~~~~~~~~~~~~
../build/xpatch.cpp:367:7: error: 'NORMALDISPLAY' was not declared in this scope
   cmd(NORMALDISPLAY);
       ^~~~~~~~~~~~~
../build/xpatch.cpp:367:7: note: suggested alternative: 'NORMALPRIO'
   cmd(NORMALDISPLAY);
       ^~~~~~~~~~~~~
       NORMALPRIO
../build/xpatch.cpp:368:7: error: 'DEACTIVATE_SCROLL' was not declared in this scope
   cmd(DEACTIVATE_SCROLL);
       ^~~~~~~~~~~~~~~~~
../build/xpatch.cpp:369:7: error: 'DISPLAYON' was not declared in this scope
   cmd(DISPLAYON);
       ^~~~~~~~~
../build/xpatch.cpp: In member function 'msg_t rootc::ThreadX2()':
../build/xpatch.cpp:396:1: warning: no return statement in function returning non-void [-Wreturn-type]
 }
 ^
../build/xpatch.cpp: In static member function 'static msg_t rootc::ThreadX(void*)':
../build/xpatch.cpp:399:35: error: 'class rootc::instanceOLED128x64__1' has no member named 'ThreadX2'
   ((instanceOLED128x64__1 *)arg)->ThreadX2();
                                   ^~~~~~~~
../build/xpatch.cpp:400:1: warning: no return statement in function returning non-void [-Wreturn-type]
 }
 ^
../build/xpatch.cpp: In member function 'void rootc::Init(rootc*)':
../build/xpatch.cpp:415:5: error: 'OPMODE_I2C' was not declared in this scope
     OPMODE_I2C,
     ^~~~~~~~~~
../build/xpatch.cpp:415:5: note: suggested alternative: 'TIME_I2S'
     OPMODE_I2C,
     ^~~~~~~~~~
     TIME_I2S
../build/xpatch.cpp:417:5: error: 'FAST_DUTY_CYCLE_2' was not declared in this scope
     FAST_DUTY_CYCLE_2,
     ^~~~~~~~~~~~~~~~~
../build/xpatch.cpp:425:88: warning: invalid conversion from 'msg_t (*)(void*)' {aka 'long int (*)(void*)'} to 'tfunc_t' {aka 'void (*)(void*)'} [-fpermissive]
 Thd = chThdCreateStatic(waThreadX, sizeof(waThreadX), NORMALPRIO, ThreadX, (void *)this);
                                                                                        ^
In file included from C:\Users\m_kor\Downloads\akso-win-3.0.1\akso-3.0.1\external/ChibiOS/os/rt/include/ch.h:117,
                 from ../firmware/patch.h:21,
                 from ../firmware/xpatch.h:2:
C:\Users\m_kor\Downloads\akso-win-3.0.1\akso-3.0.1\external/ChibiOS/os/rt/include/chthreads.h:232:53: note:   initializing argument 4 of 'thread_t* chThdCreateStatic(void*, size_t, tprio_t, tfunc_t, void*)'
../build/xpatch.cpp: At global scope:
../build/xpatch.cpp:544:6: error: 'instanceremind4__1' does not name a type; did you mean 'instancescope__1'?
      instanceremind4__1 instanceremind4__1_i;
      ^~~~~~~~~~~~~~~~~~
      instancescope__1
../build/xpatch.cpp:545:6: error: 'instanceOLED128x64__1' does not name a type; did you mean 'instancescope__1'?
      instanceOLED128x64__1 instanceOLED128x64__1_i;
      ^~~~~~~~~~~~~~~~~~~~~
      instancescope__1
../build/xpatch.cpp:551:115: error: 'display_metas' was not declared in this scope
 { name : {'s','c','o','p','e','_','1', 0 ,}, nparams : 0, params : 0, param_names : 0, ndisplays : 1, displays : &display_metas[0], nobjects : 0, objects : 0},
                                                                                                                   ^~~~~~~~~~~~~
../build/xpatch.cpp:551:115: note: suggested alternative: 'Display_meta_t'
 { name : {'s','c','o','p','e','_','1', 0 ,}, nparams : 0, params : 0, param_names : 0, ndisplays : 1, displays : &display_metas[0], nobjects : 0, objects : 0},
                                                                                                                   ^~~~~~~~~~~~~
                                                                                                                   Display_meta_t
../build/xpatch.cpp:558:23: error: 'NPRESETS' was not declared in this scope
       int32_t presets[NPRESETS][NPRESET_ENTRIES][2] = {
                       ^~~~~~~~
../build/xpatch.cpp:558:23: note: suggested alternative: 'RESET'
       int32_t presets[NPRESETS][NPRESET_ENTRIES][2] = {
                       ^~~~~~~~
                       RESET
../build/xpatch.cpp:558:33: error: 'NPRESET_ENTRIES' was not declared in this scope
       int32_t presets[NPRESETS][NPRESET_ENTRIES][2] = {
                                 ^~~~~~~~~~~~~~~
../build/xpatch.cpp: In function 'const int32_t* GetPresets()':
../build/xpatch.cpp:641:22: error: 'presets' was not declared in this scope
   return (int32_t *)&presets[0][0][0];
                      ^~~~~~~
../build/xpatch.cpp:641:22: note: suggested alternative: 'GetPresets'
   return (int32_t *)&presets[0][0][0];
                      ^~~~~~~
                      GetPresets
../build/xpatch.cpp: In function 'void ApplyPreset(int)':
../build/xpatch.cpp:648:16: error: 'nparams' was not declared in this scope
      for(i=0;i<nparams;i++){
                ^~~~~~~
../build/xpatch.cpp:649:26: error: 'PExch' was not declared in this scope
         ParameterChange(&PExch[i], p[i], 0xFFEF);
                          ^~~~~
../build/xpatch.cpp:653:16: error: 'NPRESETS' was not declared in this scope
    if (index < NPRESETS) {
                ^~~~~~~~
../build/xpatch.cpp:653:16: note: suggested alternative: 'RESET'
    if (index < NPRESETS) {
                ^~~~~~~~
                RESET
../build/xpatch.cpp:655:41: error: 'NPRESET_ENTRIES' was not declared in this scope
      PresetParamChange_t *p = &pa[index*NPRESET_ENTRIES];
                                         ^~~~~~~~~~~~~~~
../build/xpatch.cpp:659:47: error: 'nparams' was not declared in this scope
          if ((pp->pexIndex>=0)&&(pp->pexIndex<nparams)) {
                                               ^~~~~~~
../build/xpatch.cpp:660:30: error: 'PExch' was not declared in this scope
             ParameterChange(&PExch[pp->pexIndex],pp->value,0xFFEF);         }
                              ^~~~~
../build/xpatch.cpp: In function 'PExModulationTarget_t* GetModulationTable()':
../build/xpatch.cpp:666:61: error: 'NMODULATIONSOURCES' was not declared in this scope
     static const PExModulationTarget_t PExModulationSources[NMODULATIONSOURCES][NMODULATIONTARGETS] =
                                                             ^~~~~~~~~~~~~~~~~~
../build/xpatch.cpp:666:81: error: 'NMODULATIONTARGETS' was not declared in this scope
     static const PExModulationTarget_t PExModulationSources[NMODULATIONSOURCES][NMODULATIONTARGETS] =
                                                                                 ^~~~~~~~~~~~~~~~~~
../build/xpatch.cpp:675:37: error: 'PExModulationSources' was not declared in this scope
    return (PExModulationTarget_t *)&PExModulationSources[0][0];
                                     ^~~~~~~~~~~~~~~~~~~~
../build/xpatch.cpp:675:37: note: suggested alternative: 'PExModulationTarget_t'
    return (PExModulationTarget_t *)&PExModulationSources[0][0];
                                     ^~~~~~~~~~~~~~~~~~~~
                                     PExModulationTarget_t
../build/xpatch.cpp: In function 'void Init()':
../build/xpatch.cpp:679:4: error: 'instanceremind4__1_i' was not declared in this scope
    instanceremind4__1_i.Init(this );
    ^~~~~~~~~~~~~~~~~~~~
../build/xpatch.cpp:679:4: note: suggested alternative: 'instancescope__1_i'
    instanceremind4__1_i.Init(this );
    ^~~~~~~~~~~~~~~~~~~~
    instancescope__1_i
../build/xpatch.cpp:679:30: error: invalid use of 'this' in non-member function
    instanceremind4__1_i.Init(this );
                              ^~~~
../build/xpatch.cpp:680:4: error: 'instanceOLED128x64__1_i' was not declared in this scope
    instanceOLED128x64__1_i.Init(this );
    ^~~~~~~~~~~~~~~~~~~~~~~
../build/xpatch.cpp:680:4: note: suggested alternative: 'instancescope__1_i'
    instanceOLED128x64__1_i.Init(this );
    ^~~~~~~~~~~~~~~~~~~~~~~
    instancescope__1_i
../build/xpatch.cpp:680:33: error: invalid use of 'this' in non-member function
    instanceOLED128x64__1_i.Init(this );
                                 ^~~~
../build/xpatch.cpp:681:28: error: invalid use of 'this' in non-member function
    instancescope__1_i.Init(this, (int8_t *)(&displayVector[0]) );
                            ^~~~
../build/xpatch.cpp:681:46: error: 'displayVector' was not declared in this scope
    instancescope__1_i.Init(this, (int8_t *)(&displayVector[0]) );
                                              ^~~~~~~~~~~~~
../build/xpatch.cpp:681:46: note: suggested alternative: 'Display_meta_t'
    instancescope__1_i.Init(this, (int8_t *)(&displayVector[0]) );
                                              ^~~~~~~~~~~~~
                                              Display_meta_t
../build/xpatch.cpp:688:29: error: 'PExch' was not declared in this scope
       Parameter_t *param = &PExch[j];
                             ^~~~~
../build/xpatch.cpp:694:19: error: 'PExModulationPrevVal' was not declared in this scope
    int32_t *pp = &PExModulationPrevVal[0][0];
                   ^~~~~~~~~~~~~~~~~~~~
../build/xpatch.cpp:694:19: note: suggested alternative: 'PExModulationTarget_t'
    int32_t *pp = &PExModulationPrevVal[0][0];
                   ^~~~~~~~~~~~~~~~~~~~
                   PExModulationTarget_t
../build/xpatch.cpp:695:16: error: 'NMODULATIONSOURCES' was not declared in this scope
    for(j=0;j<1*NMODULATIONSOURCES;j++){
                ^~~~~~~~~~~~~~~~~~
../build/xpatch.cpp: In function 'void Dispose()':
../build/xpatch.cpp:703:4: error: 'instanceOLED128x64__1_i' was not declared in this scope
    instanceOLED128x64__1_i.Dispose();
    ^~~~~~~~~~~~~~~~~~~~~~~
../build/xpatch.cpp:703:4: note: suggested alternative: 'instancescope__1_i'
    instanceOLED128x64__1_i.Dispose();
    ^~~~~~~~~~~~~~~~~~~~~~~
    instancescope__1_i
../build/xpatch.cpp:704:4: error: 'instanceremind4__1_i' was not declared in this scope
    instanceremind4__1_i.Dispose();
    ^~~~~~~~~~~~~~~~~~~~
../build/xpatch.cpp:704:4: note: suggested alternative: 'instancescope__1_i'
    instanceremind4__1_i.Dispose();
    ^~~~~~~~~~~~~~~~~~~~
    instancescope__1_i
../build/xpatch.cpp: In function 'void dsp()':
../build/xpatch.cpp:722:3: error: 'instanceremind4__1_i' was not declared in this scope
   instanceremind4__1_i.dsp( this , 0, 0, 0 , 0 , 0 , 0 , (bool &)UNCONNECTED_OUTPUT, net0);
   ^~~~~~~~~~~~~~~~~~~~
../build/xpatch.cpp:722:3: note: suggested alternative: 'instancescope__1_i'
   instanceremind4__1_i.dsp( this , 0, 0, 0 , 0 , 0 , 0 , (bool &)UNCONNECTED_OUTPUT, net0);
   ^~~~~~~~~~~~~~~~~~~~
   instancescope__1_i
../build/xpatch.cpp:722:29: error: invalid use of 'this' in non-member function
   instanceremind4__1_i.dsp( this , 0, 0, 0 , 0 , 0 , 0 , (bool &)UNCONNECTED_OUTPUT, net0);
                             ^~~~
../build/xpatch.cpp:723:3: error: 'instanceOLED128x64__1_i' was not declared in this scope
   instanceOLED128x64__1_i.dsp( this , net0, 0, 0, 0, 0);
   ^~~~~~~~~~~~~~~~~~~~~~~
../build/xpatch.cpp:723:3: note: suggested alternative: 'instancescope__1_i'
   instanceOLED128x64__1_i.dsp( this , net0, 0, 0, 0, 0);
   ^~~~~~~~~~~~~~~~~~~~~~~
   instancescope__1_i
../build/xpatch.cpp:723:32: error: invalid use of 'this' in non-member function
   instanceOLED128x64__1_i.dsp( this , net0, 0, 0, 0, 0);
                                ^~~~
../build/xpatch.cpp:724:27: error: invalid use of 'this' in non-member function
   instancescope__1_i.dsp( this , zerobuffer, 0, (int8_t *)(&displayVector[0]));
                           ^~~~
../build/xpatch.cpp:724:61: error: 'displayVector' was not declared in this scope
   instancescope__1_i.dsp( this , zerobuffer, 0, (int8_t *)(&displayVector[0]));
                                                             ^~~~~~~~~~~~~
../build/xpatch.cpp:724:61: note: suggested alternative: 'Display_meta_t'
   instancescope__1_i.dsp( this , zerobuffer, 0, (int8_t *)(&displayVector[0]));
                                                             ^~~~~~~~~~~~~
                                                             Display_meta_t
../build/xpatch.cpp: At global scope:
../build/xpatch.cpp:733:1: error: expected declaration before '}' token
 };
 ^
make: *** [Makefile.patch:105: ../build/xpatch.o] Error 1
Compiling patch failed.
shell task failed, exit value: 1
axoloti.shell.ExecutionFailedException
axoloti.shell.ExecutionFailedException
	at axoloti.shell.ShellTask.run(ShellTask.java:120)
	at axoloti.shell.ShellTask.lambda$getJob$0(ShellTask.java:37)
	at axoloti.shell.CompilePatch.lambda$run$0(CompilePatch.java:67)
	at java.base/java.lang.Thread.run(Thread.java:834)

axoloti.shell.ExecutionFailedException
axoloti.shell.ExecutionFailedException
	at axoloti.shell.CompilePatch.run(CompilePatch.java:75)
	at axoloti.live.patch.PatchViewLive.lambda$goLive$7(PatchViewLive.java:275)
	at axoloti.job.JobProcessor.lambda$exec$0(JobProcessor.java:21)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

[oled issue.zip](https://github.com/zrna-research/akso-community/files/5321772/oled.issue.zip)

`

**Comment by kaosbeat** [comment]
Hi,

I edited the object akso-3.0.1
`/akso-community/objects/tiar/HW/OLED128x64niceWOScope.axo`
to have non-conflicting defines at the top. I added a t to both names. They are already defined in axoloti_control.h and this is somehow a conflict
 
```
LCDWIDTHt            = 128,
LCDHEIGHTt           = 64,
```

somehow it compiles without errors and the patch is running now, although, might be good to know :) the display is not working.
The same trick on the object with scope did not work...

If I try the trick the other way around (editing axoloti_control.h) compilation does not even start. No output in the AKSO window but some errors in the akso terminal window

```
xception in thread "AWT-EventQueue-0" java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 0
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
	at java.base/java.lang.String.substring(String.java:1874)
	at axoloti.object.AxoObject.getProcessedIncludes(AxoObject.java:423)
	at axoloti.patch.PatchModel.getIncludes(PatchModel.java:434)
	at axoloti.codegen.patch.PatchViewCodegen.generateIncludes(PatchViewCodegen.java:95)
	at axoloti.codegen.patch.PatchViewCodegen.generateCode4(PatchViewCodegen.java:764)
	at axoloti.patch.PatchController.writeCode(PatchController.java:199)
	at axoloti.patch.PatchController.writeCode(PatchController.java:157)
	at axoloti.swingui.patch.PatchFrame.goLive(PatchFrame.java:1181)
	at axoloti.swingui.patch.PatchFrame.jCheckBoxLiveActionPerformed(PatchFrame.java:834)
	at axoloti.swingui.patch.PatchFrame.access$800(PatchFrame.java:87)
	at axoloti.swingui.patch.PatchFrame$15.actionPerformed(PatchFrame.java:565)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:401)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6635)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6400)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
